Write-host "Hello Anuj Chachu"
Write-host "You are Hacked"
Write-host "Sachin is here"
Write-host "Cybersecurity Expert"
Write-host "Call me right now"
Write-host "Phone number is 1234567890"
Write-host "Your Computer/Laptop is compromised by me"
Write-host "It is only for Educational Purposes"
Write-host "Thank You"